# Generated by Django 3.0.6 on 2020-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
